# Form implementation generated from reading ui file 'bankAccGui.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, bankAccount):
        bankAccount.setObjectName("bankAccount")
        bankAccount.resize(392, 729)
        bankAccount.setStyleSheet("background-color: rgb(250,250,255)")
        self.centralwidget = QtWidgets.QWidget(parent=bankAccount)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 391, 731))
        self.stackedWidget.setObjectName("stackedWidget")
        self.loginPage = QtWidgets.QWidget()
        self.loginPage.setObjectName("loginPage")
        self.welcomeLabel = QtWidgets.QLabel(parent=self.loginPage)
        self.welcomeLabel.setGeometry(QtCore.QRect(40, 20, 321, 81))
        self.welcomeLabel.setStyleSheet("color: rgb(250, 250, 255);\n"
"border: 2px solid rgb(240,197,113);\n"
"font: 20pt \"Verdana\";\n"
"background-color: rgb(14, 11, 128);\n"
"border-radius: 8px")
        self.welcomeLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.welcomeLabel.setWordWrap(True)
        self.welcomeLabel.setObjectName("welcomeLabel")
        self.usernameEntry = QtWidgets.QLineEdit(parent=self.loginPage)
        self.usernameEntry.setGeometry(QtCore.QRect(40, 210, 321, 31))
        self.usernameEntry.setStyleSheet("border: 2px solid rgb(240,197,113);\n"
"color: rgb(14, 11, 128)")
        self.usernameEntry.setObjectName("usernameEntry")
        self.usernameLabel_2 = QtWidgets.QLabel(parent=self.loginPage)
        self.usernameLabel_2.setGeometry(QtCore.QRect(40, 170, 321, 31))
        self.usernameLabel_2.setStyleSheet("color: rgb(14,11,128);\n"
"font: 13pt \"Verdana\";\n"
"border-bottom: 5px solid rgb(14,11,128);")
        self.usernameLabel_2.setObjectName("usernameLabel_2")
        self.passwordEntry = QtWidgets.QLineEdit(parent=self.loginPage)
        self.passwordEntry.setGeometry(QtCore.QRect(40, 290, 321, 31))
        self.passwordEntry.setStyleSheet("border: 2px solid rgb(240,197,113);\n"
"color: rgb(14, 11, 128)")
        self.passwordEntry.setClearButtonEnabled(False)
        self.passwordEntry.setObjectName("passwordEntry")
        self.passwordLabel = QtWidgets.QLabel(parent=self.loginPage)
        self.passwordLabel.setGeometry(QtCore.QRect(40, 250, 321, 31))
        self.passwordLabel.setStyleSheet("color: rgb(14,11,128);\n"
"font: 13pt \"Verdana\";\n"
"border-bottom: 5px solid rgb(14,11,128);")
        self.passwordLabel.setObjectName("passwordLabel")
        self.passwordEntryLabel = QtWidgets.QLabel(parent=self.loginPage)
        self.passwordEntryLabel.setGeometry(QtCore.QRect(40, 320, 321, 51))
        self.passwordEntryLabel.setStyleSheet("color: rgb(14,11,128);\n"
"font: 10pt \"Verdana\";\n"
"")
        self.passwordEntryLabel.setWordWrap(True)
        self.passwordEntryLabel.setObjectName("passwordEntryLabel")
        self.submitButton = QtWidgets.QPushButton(parent=self.loginPage)
        self.submitButton.setGeometry(QtCore.QRect(40, 690, 311, 31))
        self.submitButton.setStyleSheet("background-color: rgb(14, 11, 128);\n"
"border: 2px solid rgb(240, 197,113);\n"
"color: rgb(250, 250, 250);\n"
"font: 13pt Verdana;\n"
"border-radius: 8px;")
        self.submitButton.setObjectName("submitButton")
        
        self.loginButton = QtWidgets.QPushButton(parent=self.loginPage)
        self.loginButton.setGeometry(QtCore.QRect(40, 370, 311, 31))
        self.loginButton.setStyleSheet("background-color: rgb(14, 11, 128);\n"
"border: 2px solid rgb(240, 197,113);\n"
"color: rgb(250, 250, 250);\n"
"font: 13pt Verdana;\n"
"border-radius: 8px;")
        self.loginButton.setObjectName("loginButton")
        
        
        self.passwordSUentry = QtWidgets.QLineEdit(parent=self.loginPage)
        self.passwordSUentry.setGeometry(QtCore.QRect(40, 650, 321, 31))
        self.passwordSUentry.setStyleSheet("border: 2px solid rgb(240,197,113);\n"
"")
        self.passwordSUentry.setClearButtonEnabled(False)
        self.passwordSUentry.setObjectName("passwordSUlabel_2")
        self.usernameSUlabel = QtWidgets.QLabel(parent=self.loginPage)
        self.usernameSUlabel.setGeometry(QtCore.QRect(40, 530, 321, 31))
        self.usernameSUlabel.setStyleSheet("color: rgb(14,11,128);\n"
"font: 13pt \"Verdana\";\n"
"border-bottom: 5px solid rgb(14,11,128);")
        self.usernameSUlabel.setObjectName("usernameSUlabel")
        self.usernameSUentry = QtWidgets.QLineEdit(parent=self.loginPage)
        self.usernameSUentry.setGeometry(QtCore.QRect(40, 570, 321, 31))
        self.usernameSUentry.setStyleSheet("border: 2px solid rgb(240,197,113);\n"
"")
        self.usernameSUentry.setObjectName("usernameSUentry")
        self.passwordSUlabel = QtWidgets.QLabel(parent=self.loginPage)
        self.passwordSUlabel.setGeometry(QtCore.QRect(40, 610, 321, 31))
        self.passwordSUlabel.setStyleSheet("color: rgb(14,11,128);\n"
"font: 13pt \"Verdana\";\n"
"border-bottom: 5px solid rgb(14,11,128);")
        self.passwordSUlabel.setObjectName("passwordSUlabel")
        self.loginLabel = QtWidgets.QLabel(parent=self.loginPage)
        self.loginLabel.setGeometry(QtCore.QRect(40, 120, 331, 41))
        self.loginLabel.setStyleSheet("color: rgb(14,11,128);\n"
"font: 20pt \"Verdana\";\n"
"border-bottom: 5px solid rgb(14,11,128);")
        self.loginLabel.setObjectName("loginLabel")
        self.signUpLabel = QtWidgets.QLabel(parent=self.loginPage)
        self.signUpLabel.setGeometry(QtCore.QRect(40, 480, 331, 41))
        self.signUpLabel.setStyleSheet("color: rgb(14,11,128);\n"
"font: 20pt \"Verdana\";\n"
"border-bottom: 5px solid rgb(14,11,128);")
        self.signUpLabel.setObjectName("signUpLabel")
        self.stackedWidget.addWidget(self.loginPage)
        self.homePage = QtWidgets.QWidget()
        self.homePage.setObjectName("homePage")
        self.amountLabel3 = QtWidgets.QLabel(parent=self.homePage)
        self.amountLabel3.setGeometry(QtCore.QRect(150, 415, 60, 21))
        self.amountLabel3.setStyleSheet("color: rgb(14, 11, 128);\n"
"font: 13pt Verdana;\n"
"border-bottom: 3px solid rgb(14,11,128);")
        self.amountLabel3.setObjectName("amountLabel3")
        self.savingsNameBalanceLabel = QtWidgets.QLabel(parent=self.homePage)
        self.savingsNameBalanceLabel.setGeometry(QtCore.QRect(40, 260, 321, 31))
        self.savingsNameBalanceLabel.setStyleSheet("color: rgb(14,11,128);\n"
"font: 13pt \"Verdana\";\n"
"border: 2px solid rgb(152,181,217);\n"
"border-radius: 8px;")
        self.savingsNameBalanceLabel.setObjectName("savingsNameBalanceLabel")
        self.depositAmt = QtWidgets.QLineEdit(parent=self.homePage)
        self.depositAmt.setGeometry(QtCore.QRect(220, 326, 113, 31))
        self.depositAmt.setStyleSheet("color: rgb(14, 11, 128);\n"
"font: 13pt Verdana;\n"
"border: 2px solid rgb(14, 11, 128);\n"
"border-radius: 8px;")
        self.depositAmt.setText("")
        self.depositAmt.setObjectName("depositAmt")
        self.checkingLabel = QtWidgets.QLabel(parent=self.homePage)
        self.checkingLabel.setGeometry(QtCore.QRect(40, 130, 321, 31))
        self.checkingLabel.setStyleSheet("color: rgb(14,11,128);\n"
"font: 13pt \"Verdana\";\n"
"border-bottom: 5px solid rgb(14,11,128);")
        self.checkingLabel.setObjectName("checkingLabel")
        self.withdrawAmt = QtWidgets.QLineEdit(parent=self.homePage)
        self.withdrawAmt.setGeometry(QtCore.QRect(220, 366, 113, 31))
        self.withdrawAmt.setStyleSheet("color: rgb(14, 11, 128);\n"
"font: 13pt Verdana;\n"
"border: 2px solid rgb(14, 11, 128);\n"
"border-radius: 8px;")
        self.withdrawAmt.setText("")
        self.withdrawAmt.setObjectName("withdrawAmt")
        self.transferAmt = QtWidgets.QLineEdit(parent=self.homePage)
        self.transferAmt.setGeometry(QtCore.QRect(220, 410, 113, 31))
        self.transferAmt.setStyleSheet("color: rgb(14, 11, 128);\n"
"font: 13pt Verdana;\n"
"border: 2px solid rgb(14, 11, 128);\n"
"border-radius: 8px;")
        self.transferAmt.setText("")
        self.transferAmt.setObjectName("transferAmt")
        self.label_25 = QtWidgets.QLabel(parent=self.homePage)
        self.label_25.setGeometry(QtCore.QRect(110, 560, 181, 91))
        self.label_25.setObjectName("label_25")
        self.savingsLabel = QtWidgets.QLabel(parent=self.homePage)
        self.savingsLabel.setGeometry(QtCore.QRect(40, 220, 321, 31))
        self.savingsLabel.setStyleSheet("color: rgb(14,11,128);\n"
"font: 13pt \"Verdana\";\n"
"border-bottom: 5px solid rgb(14,11,128);")
        self.savingsLabel.setObjectName("savingsLabel")
        self.nameBalanceLabel = QtWidgets.QLabel(parent=self.homePage)
        self.nameBalanceLabel.setGeometry(QtCore.QRect(40, 170, 321, 31))
        self.nameBalanceLabel.setStyleSheet("color: rgb(14,11,128);\n"
"font: 13pt \"Verdana\";\n"
"border: 2px solid rgb(152,181,217);\n"
"border-radius: 8px;\n"
"")
        self.nameBalanceLabel.setObjectName("nameBalanceLabel")
        self.withdrawButton = QtWidgets.QPushButton(parent=self.homePage)
        self.withdrawButton.setGeometry(QtCore.QRect(30, 366, 113, 32))
        self.withdrawButton.setStyleSheet("background-color: rgb(14, 11, 128);\n"
"border: 2px solid rgb(240, 197,113);\n"
"color: rgb(250, 250, 250);\n"
"font: 13pt Verdana;\n"
"border-radius: 8px;")
        self.withdrawButton.setObjectName("withdrawButton")
        self.depositButton = QtWidgets.QPushButton(parent=self.homePage)
        self.depositButton.setGeometry(QtCore.QRect(30, 326, 113, 32))
        self.depositButton.setStyleSheet("background-color: rgb(14, 11, 128);\n"
"border: 2px solid rgb(240, 197,113);\n"
"color: rgb(250, 250, 250);\n"
"font: 13pt Verdana;\n"
"border-radius: 8px;")
        self.depositButton.setObjectName("depositButton")
        self.amountLabel1 = QtWidgets.QLabel(parent=self.homePage)
        self.amountLabel1.setGeometry(QtCore.QRect(150, 332, 60, 20))
        self.amountLabel1.setStyleSheet("color: rgb(14, 11, 128);\n"
"font: 13pt Verdana;\n"
"border-bottom: 3px solid rgb(14,11,128);")
        self.amountLabel1.setObjectName("amountLabel1")
        self.interestLabel = QtWidgets.QLabel(parent=self.homePage)
        self.interestLabel.setGeometry(QtCore.QRect(30, 460, 341, 31))
        self.interestLabel.setStyleSheet("color: rgb(14,11,128);\n"
"font: 13pt \"Verdana\";\n"
"border-bottom: 5px solid rgb(14,11,128);\n"
"border-top: 5px solid rgb(14,11,128);")
        self.interestLabel.setObjectName("interestLabel")
        self.balanceChart = QtWidgets.QGraphicsView(parent=self.homePage)
        self.balanceChart.setGeometry(QtCore.QRect(70, 510, 256, 192))
        self.balanceChart.setObjectName("balanceChart")
        self.amountLabel2 = QtWidgets.QLabel(parent=self.homePage)
        self.amountLabel2.setGeometry(QtCore.QRect(150, 372, 60, 20))
        self.amountLabel2.setStyleSheet("color: rgb(14, 11, 128);\n"
"font: 13pt Verdana;\n"
"border-bottom: 3px solid rgb(14,11,128);")
        self.amountLabel2.setObjectName("amountLabel2")
        self.accountLabel = QtWidgets.QLabel(parent=self.homePage)
        self.accountLabel.setGeometry(QtCore.QRect(30, 80, 331, 41))
        self.accountLabel.setStyleSheet("color: rgb(14,11,128);\n"
"font: 20pt \"Verdana\";\n"
"border-bottom: 5px solid rgb(14,11,128);")
        self.accountLabel.setObjectName("accountLabel")
        self.transferButton = QtWidgets.QPushButton(parent=self.homePage)
        self.transferButton.setGeometry(QtCore.QRect(30, 406, 113, 32))
        self.transferButton.setStyleSheet("background-color: rgb(14, 11, 128);\n"
"border: 2px solid rgb(240, 197,113);\n"
"color: rgb(250, 250, 250);\n"
"font: 13pt Verdana;\n"
"border-radius: 8px;")
        self.transferButton.setObjectName("transferButton")
        self.balanceLabel = QtWidgets.QLabel(parent=self.homePage)
        self.balanceLabel.setGeometry(QtCore.QRect(30, 10, 331, 61))
        self.balanceLabel.setStyleSheet("color: rgb(250, 250, 255);\n"
"border: 2px solid rgb(240,197,113);\n"
"font: 20pt \"Verdana\";\n"
"background-color: rgb(14, 11, 128);\n"
"border-radius: 8px")
        self.balanceLabel.setObjectName("balanceLabel")
        self.stackedWidget.addWidget(self.homePage)
        bankAccount.setCentralWidget(self.centralwidget)

        self.retranslateUi(bankAccount)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(bankAccount)

    def retranslateUi(self, bankAccount):
        _translate = QtCore.QCoreApplication.translate
        bankAccount.setWindowTitle(_translate("bankAccount", "MainWindow"))
        self.welcomeLabel.setText(_translate("bankAccount", "Welcome to                    Computer Science Bank"))
        self.usernameEntry.setPlaceholderText(_translate("bankAccount", "Enter username"))
        self.usernameLabel_2.setText(_translate("bankAccount", "Username"))
        self.passwordEntry.setPlaceholderText(_translate("bankAccount", "Enter password"))
        self.passwordLabel.setText(_translate("bankAccount", "Password"))
        self.passwordEntryLabel.setText(_translate("bankAccount", "Password must be 7 characters long and contain at least one number and one symbol"))
        self.submitButton.setText(_translate("bankAccount", "Submit"))
        self.loginButton.setText(_translate("bankAccount", "Login"))
        self.passwordSUentry.setPlaceholderText(_translate("bankAccount", "Enter password"))
        self.usernameSUlabel.setText(_translate("bankAccount", "Username"))
        self.usernameSUentry.setPlaceholderText(_translate("bankAccount", "Enter username"))
        self.passwordSUlabel.setText(_translate("bankAccount", "Password"))
        self.loginLabel.setText(_translate("bankAccount", "LOGIN"))
        self.signUpLabel.setText(_translate("bankAccount", "SIGN UP"))
        self.amountLabel3.setText(_translate("bankAccount", "Amount: "))
        self.savingsNameBalanceLabel.setText(_translate("bankAccount", "Name - Balance"))
        self.checkingLabel.setText(_translate("bankAccount", "Checking "))
        self.label_25.setText(_translate("bankAccount", "Balance over time chart"))
        self.savingsLabel.setText(_translate("bankAccount", "Savings "))
        self.nameBalanceLabel.setText(_translate("bankAccount", "Name - Balance"))
        self.withdrawButton.setText(_translate("bankAccount", "Withdraw"))
        self.depositButton.setText(_translate("bankAccount", "Deposit"))
        self.amountLabel1.setText(_translate("bankAccount", "Amount: "))
        self.interestLabel.setText(_translate("bankAccount", "Deposits Until Interest: 3"))
        self.amountLabel2.setText(_translate("bankAccount", "Amount: "))
        self.accountLabel.setText(_translate("bankAccount", "Accounts"))
        self.transferButton.setText(_translate("bankAccount", "Transfer"))
        self.balanceLabel.setText(_translate("bankAccount", "Balance: $0.00"))
